id: I50DE0866
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T17:20:55.166861'
last_modified: '2022-05-27T17:20:55.166904'
parser: null
source_metadata:
  title: 'MSV 1,09: Kośāmbakavastu'
  language: bo
  base:
    f8E5E:
      title: Kośāmbakavastu
      base_file: f8E5E.txt
      order: 1
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
